Feature/rooms 16 make forum page
rpserjo/praktikum-game pull request #12
Opened 2023-06-07 21:58 UTC by RuslanBely

### Какую задачу решаем
ROOMS-16 Верстка страницы форума.
https://linear.app/the-rooms/issue/ROOMS-16/vyorstka-stranicy-foruma

- Создана страница форума forum с пагинацией, реализовано модальное окно для создания новой темы
- Создана страница топика форума с пагинацией, реализовано модальное окно для добавления сообщений
- Добавлены компоненты Input, Textarea
- Добавлены моковые данные для тем и сообщений форума
- Добавлен helper для работы с преобразованием формат дат.

### Скриншоты/видяшка (если есть)

![image](https://github.com/rpserjo/praktikum-game/assets/126679894/14fde6d0-c5c2-4fc0-ba9b-18efd4cbf9e2)

![image](https://github.com/rpserjo/praktikum-game/assets/126679894/6cafe948-f46f-49ba-8972-48c3a27bf04e)

### TBD (если есть)

2023-06-08 18:35 UTC, rpserjo approved these changes

2023-06-08 18:35 UTC, rpserjo commented on packages/client/src/components/ui/input/input.tsx
> +    label: string;
Может сделать это пропс необязательным, чтобы при необходимости можно было создавать input без лейбла?

2023-06-08 18:35 UTC, rpserjo commented on packages/client/src/helpers/dateformat.ts
> +    DATE = '01 января 2023 01:01',
Мне кажется, или семантически названия перепутаны?)

2023-06-08 18:35 UTC, rpserjo commented on packages/client/src/pages/forum-topic/forum-topic.module.scss
> +@use '@/assets/variables' as mixin;
Вопрос вкуса, но у нас получается в разных файла по разному - то use, то import. Надо прийти к соглашению и везде писать одинаково)

2023-06-08 18:35 UTC, rpserjo commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +            <div className={newMsgModalClasses}>
По хорошему, надо бы модалку вынести в отдельный компонент. Но это уже дело под отдельную задачу

2023-06-09 10:21 UTC, RuslanBely commented on packages/client/src/components/ui/input/input.tsx
> +    label: string;
Принято, сделал

2023-06-09 10:25 UTC, RuslanBely commented on packages/client/src/helpers/dateformat.ts
> +    DATE = '01 января 2023 01:01',
Есть такое, исправлено

2023-06-09 10:30 UTC, RuslanBely commented on packages/client/src/pages/forum-topic/forum-topic.module.scss
> +@use '@/assets/variables' as mixin;
Согласен, переделал на @import

2023-06-09 10:32 UTC, RuslanBely commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +            <div className={newMsgModalClasses}>
По хорошему да, как и подумать о выносе пагинации. Сейчас не хватило времени на это, нужно цеплять еще другие ветки для выноса.

2023-06-10 09:29 UTC, bin-umar requested changes
Привет! Я ревьюер из Я.Практикума.

Немного мелких стилистических ошибок, прощу их учесть и исправить. Насчёт дизайн токенов можете с командой договориться и решить стоит ли, но как минимум цветов стоит (лучше в этом ПР-е конечно), и их необходимо переименовать в правильные названия.
Также из рекомендованных это БЭМ, на ваше усмотрение с командой. В остальном всё в пределах нормы.

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/button/button.tsx
> +    type?: 'button' | 'submit' | 'reset' | undefined;
Сам оператор optional уже добавляет значение undefined.
```suggestion
    type?: 'button' | 'submit' | 'reset';
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/button/button.tsx
> +    <button onClick={onClick} type={type} className={`${style[buttonStyle]} ${style[buttonSize]}`}>
Мне кажется вам стоит начать использовать https://www.npmjs.com/package/clsx, в конкретном примере можно и без него, но в перспективе он вам точно понадобится.
```suggestion
    <button onClick={onClick} type={type} className={clsx(style[buttonStyle], style[buttonSize])}>
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/input/input.module.scss
> +  padding:0 0 2px 2px;
Не только js код нуждается в красивом форматирование :)
```suggestion
.input-wrapper {
  width: 100%;

  .label {
     display: block;
     padding: 0 0 2px 2px;
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/input/input.module.scss
> +  font-size: 16px;
Не хватает line-height. https://learn.javascript.ru/font-size-line-height

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/input/input.module.scss
> +  font-size: 16px;
В целом типографику в идеале лучше перенести в [дизайн-токены ](https://paradigm.mail.ru/design_tokens)(переменные) и сделать отдельные компоненты под h2, h3,  и т.д. https://paradigm.mail.ru/design_tokens/typography

P.S. Компоненты сделать необязательно (по крайней мере пока что, но вот в переменные вынести желательно)

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/input/input.module.scss
> +  font-size: 16px;
Посмотри например https://mui.com/material-ui/react-typography/, у них один компонент для текстов с помощью которого можно нарисовать разные текста. Но самое главное что у вас во всём проекте будет одни и те ж размеры h2, h3, h1 и т.д. У вас будет меньше дублирование кода и единая точка компонентов.

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/input/input.tsx
> +    classNameLabel?: string;
По идеологии UI компонентов лучше не давать возможности передавать кастомные классы, потому что через кастомные классы их можно изменить до неузнаваемости. А один из основных смыслов перенесение их в одну точку это добиться единого вида компонентов во всём проекте. Если понадобиться разные вариации инпута, то лучше добавить эти вариации в самом компоненты инпут, а кастомизацию сделать через пропсы. Таким образом вы сможете гарантировать что у вас везде будет одни и те ж компоненты. Ну и в случае редизайна тоже сможете легко изменить их в одном месте.

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/textarea/textarea.module.scss
> +}
Рекомендую называть классы по [БЭМ](https://ru.bem.info/methodology/quick-start/#%D0%B1%D0%BB%D0%BE%D0%BA)-у
```suggestion
.textarea-block {
  &__label {
    display: block;
    padding:0 0 2px 2px;
    font-size: 16px;
    font-weight: 500;
  }


  &__input {
    all: unset;
    box-sizing: border-box;
    background-color: $colorMain;
    display: block;
    border-radius: 5px;
    padding: 7px;
    font-size: 16px;
  }
}
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/helpers/dateformat.ts
> +        : (min = date.getMinutes().toString());
```suggestion
    const minutesStr = date.getMinutes().toString();
    const minutes = minutesStr.padStart(2, '0');
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/helpers/dateformat.ts
> +    ];
Лучше вынести над функции это.

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/helpers/dateformat.ts
> +    return undefined;
Аргумент format у вас не опциональный, так что в любом случае его надо будет передать. Поэтому нет необходимости в последнем if-е
```suggestion
    return `${dd} ${monthName} ${yyyy}`;
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/layout/default/layout.tsx
> +            <Link to="/wrong-path">404</Link>
Рекомендую роуты добавить в enum
```ts
enum Route {
   Forum = '/forum'
   NotFound = '/not-found'
}
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/mocks/mock-server.ts
> +                .reduce((r, o) => {
Мб можно проще?
```suggestion
        const topicList = this.forumData.reduce((r, o) => {
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/mocks/mock-server.ts
> +                        topic: o.topic,
Не стоит называть переменные однобуквенными. Прочитай [статейку](https://learn.javascript.ru/ninja-code#odnobukvennye-peremennye), понравиться :)

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/mocks/mock-server.ts
> +                        dateLstMsg: o.createDate,
```suggestion
                        dateLastMessage: o.createDate,
```
Ниндзя-код))

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/mocks/mock-server.ts
> +        return topicData;
```suggestion
        return this.forumData.filter(({ topicId }) => topicId === id);
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/pages/forum-topic/forum-topic.module.scss
> +        background: rgba(26, 26, 26, 0.6);
Все цвета стоит перенести в [переменные](https://paradigm.mail.ru/design_tokens/colors).

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +    };
Тайпинги стоит написать над функцией, внутри функции не очень красивая практика

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +            <div className={newMsgModalClasses}>
> По хорошему да, как и подумать о выносе пагинации. Сейчас не хватило времени на это, нужно цеплять еще другие ветки для выноса.

Да, точно. Пагинацию стоит вынести.

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +    const isShowNext = page && +page < lastPage ? true : undefined;
Мне кажется всё это можно упростить
```suggestion
    const isShowNext = page && +page < lastPage;
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +    const lastPage = Math.ceil(topicData.length / 10);
Цифру 10 стоит вынести в константы
```ts
const MAX_ELEMENTS_PER_PAGE = 10;
```

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/pages/forum/forum.module.scss
> +                    color: $colorYellow;
В чём смысл наименовать переменные по названиям цветов? Ведь их также можно использовать напрямую и без переменных.

Основной смысл этих переменных это выделение цветов в дизайн-токены. А смысл дизайн токенов в том чтобы в случае редизайна или изменения конкретного значения токена изменился бы в одном месте.
То есть задача состоит не в том чтобы все белые цвета перевести в одну переменную, черные во вторую, и т.д. Потому что например мы можем использовать белый цвет как background, так и в качестве цвет текста основного наших кнопок. В таком случае совершенно валидно и правильно разделить их в две разные переменные:
- colorBg
- colorButtonText

Иными словами не стоит группировать по значению, так как это бессмысленно, а надо по css свойствам.

В качестве примера можешь посмотреть https://paradigm.mail.ru/design_tokens/colors, можешь на его примере убедиться что белый цвет например используется в трёх разных токенах.

2023-06-10 09:29 UTC, bin-umar commented on packages/client/src/components/ui/button/button.tsx
> +    <button onClick={onClick} type={type} className={`${style[buttonStyle]} ${style[buttonSize]}`}>
Вижу что ниже используется classnames. Лучше использовать его везде.

2023-06-10 16:18 UTC, RuslanBely commented on packages/client/src/components/ui/button/button.tsx
> +    type?: 'button' | 'submit' | 'reset' | undefined;
Понял, спасибо

2023-06-10 16:21 UTC, RuslanBely commented on packages/client/src/components/ui/input/input.module.scss
> +  padding:0 0 2px 2px;
Согласен, все возлагаю надежды на prettier, нужно будет глянуть сможет ли он делать это за меня)

2023-06-10 16:39 UTC, RuslanBely commented on packages/client/src/components/ui/input/input.tsx
> +    classNameLabel?: string;
В данном случае наилучшим решением для задания отступов будет являться кастомизация через пропсы или через обертку?  Речь о margin, padding, flex и т.д.

2023-06-10 20:32 UTC, RuslanBely commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +    const lastPage = Math.ceil(topicData.length / 10);
Согласен, сделано

2023-06-10 20:36 UTC, RuslanBely commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +    const isShowNext = page && +page < lastPage ? true : undefined;
Как оказалось, да) Спасибо

2023-06-10 21:07 UTC, RuslanBely commented on packages/client/src/components/ui/input/input.module.scss
> +  font-size: 16px;
> Не хватает line-height. https://learn.javascript.ru/font-size-line-height

Данное предложение не очень, понял. Смысл в том, чтоб не полагаться на значение line-height:normal, которое применяет браузер?

2023-06-10 21:08 UTC, RuslanBely commented on packages/client/src/components/ui/textarea/textarea.module.scss
> +}
Спасибо, покопаю как совместить  в реакте scss модули и БЭМ

2023-06-10 21:12 UTC, RuslanBely commented on packages/client/src/pages/forum-topic/forum-topic.module.scss
> +        background: rgba(26, 26, 26, 0.6);
Сделано.

2023-06-10 21:14 UTC, RuslanBely commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +    };
Спасибо, поправил.

2023-06-10 22:40 UTC, bin-umar commented on packages/client/src/components/ui/input/input.tsx
> +    classNameLabel?: string;
Padding через props-ы (например если хочешь разные размеры кнопок, big, small, normal, etc.), но внешние отступы через обёртки так как компоненту не важно куда он встраивается, это забота родителя.

2023-06-10 22:42 UTC, bin-umar commented on packages/client/src/components/ui/textarea/textarea.module.scss
> +}
БЭМ это методология, т.е. как лучше наименовать css классы чтобы они были очевидными и понятными.

2023-06-11 11:54 UTC, RuslanBely commented on packages/client/src/helpers/dateformat.ts
> +        : (min = date.getMinutes().toString());
Спасибо, так значительно короче.

2023-06-11 11:58 UTC, RuslanBely commented on packages/client/src/helpers/dateformat.ts
> +    return undefined;
Принято, спасибо.

2023-06-11 12:40 UTC, RuslanBely commented on packages/client/src/mocks/mock-server.ts
> +                .reduce((r, o) => {
Не понимаю сходу предложения по укрощению. У меня есть массив объектов. Мне нужно сгруппировать данные по topicId и посчитать количество сообщений, для этого использую Map, передаю туда в качестве ключа topicId, на выходе мне нужен массив, эго получаем через ...Map.

2023-06-11 12:42 UTC, RuslanBely commented on packages/client/src/mocks/mock-server.ts
> +                        topic: o.topic,
Понял, принял - безумный копипаст со stackoverflow)

2023-06-11 12:48 UTC, RuslanBely commented on packages/client/src/mocks/mock-server.ts
> +                        dateLstMsg: o.createDate,
Понял, принял, исправил.

2023-06-11 12:50 UTC, RuslanBely commented on packages/client/src/mocks/mock-server.ts
> +        return topicData;
Согласен, так короче

2023-06-11 20:16 UTC, RuslanBely commented on packages/client/src/pages/forum-topic/forum-topic.tsx
> +            <div className={newMsgModalClasses}>
Вынес

2023-06-11 20:18 UTC, RuslanBely commented on packages/client/src/pages/forum/forum.module.scss
> +                    color: $colorYellow;
Вынесли из переменных цветов в цвета по дизайн токенам

2023-06-11 20:33 UTC, RuslanBely commented on packages/client/src/layout/default/layout.tsx
> +            <Link to="/wrong-path">404</Link>
Добавлено

2023-06-12 11:05 UTC, bin-umar commented on packages/client/src/mocks/mock-server.ts
> +                .reduce((r, o) => {
Сходу не видел Map,  по ... не очень понятно. Наверное лучше использовать Array.from

2023-06-12 11:06 UTC, bin-umar approved these changes

2023-06-12 12:50 UTC, bin-umar commented on packages/client/src/components/ui/input/input.module.scss
> +  font-size: 16px;
Был не прав, забыл про дефолтное поведение. Обычно в большинство случаев указывают желаемый line-height, но можно и так.

2023-06-12 12:50 UTC, merged