feature/ROOMS-25_canvas_dev
rpserjo/praktikum-game pull request #13
Opened 2023-06-09 10:52 UTC by OlegPeunov

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-10 15:18 UTC, practicum-maxim-zyryanov requested changes
Ох... только один файл из 73 относится к логике игры. Зачем отправлять такой пул реквест? Не сложно ведь вынести всё лишнее. Поэтому прошу переделать пул реквест, оставив в нём только решение задачи. 

Теперь по коду игры... его определенно можно сделать лучше, и главные проблемы сейчас "магические числа" и необъяснимая сложность.

2023-06-10 15:18 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/game/game.tsx
> +            const ctx = ref.current.getContext('2d');
Не стоит везде писать `ctx!`, лучше добавь проверку сразу после получения, что тот не null, не undefined и т.д. и делай return или выбрасывай ошибку.

2023-06-10 15:18 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/game/game.tsx
> +            roundRect(200, 0, 800, 400, 10);
Если далее в игре не будет таких закругленных прямоугольников, то этот код лишний. Можно расположить canvas в `div` элементе, который скруглить классическими средствами css.

2023-06-10 15:18 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/game/game.tsx
> +            renderBattlefield(250, 70);
Много "магических чисел", все стоит вынести в константы. К слову, на внутреннем ревью на это обращали внимание. И это относится не только к этому фрагменту, а к коду в целом.

2023-06-10 15:18 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/game/game.tsx
> +            const textH = 'A B C D E F G H I G';
Короткие наименования, как `textH`, использовать не очень хорошо, т.к. они очевидны только тебе.

2023-06-10 15:18 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/game/game.tsx
> +            [...Array(2).keys()].forEach(i => fillTextWithSpacing(ctx!, textH, 257 + 400 * i, 63, 6.6));
Круто, но вновь решаешь задачу очень сложными методами

2023-06-10 15:18 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/game/game.tsx
> +            });
Ты обособил кусок комментарием, но что мешало сразу сделать функцию `renderHorizontalText`

2023-06-10 15:18 UTC, practicum-maxim-zyryanov commented on packages/client/src/pages/game/game.tsx
> +            });
Имеет место быть функция `renderShips`

2023-06-11 06:18 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +            const ctx = ref.current.getContext('2d');
Привет, спасибо, добавил проверку: 
      if(ctx === null || ctx === undefined){
                return
            }

2023-06-11 06:22 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +            roundRect(200, 0, 800, 400, 10);
canvas шире чем это поле скругления, т.к. корабли, которые буду драгЭндДропатсья, находятся за скругленными полями:
https://prnt.sc/7ptXIig3j2oM
(картинка по vpn)

2023-06-11 06:44 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +            [...Array(2).keys()].forEach(i => fillTextWithSpacing(ctx!, textH, 257 + 400 * i, 63, 6.6));
Прошерстил пол интеренета, на тему letter спэйсинга в канвасе, самым оптимальным показалась такая функция.
Хотел бы сохранить её для потомков)
Чтобы она код не замусоривала, вынес в helpers

2023-06-11 06:49 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +            renderBattlefield(250, 70);
спасибо, поправил:
              const fieldSize = 30;
              const screenSize = 300;

              for (let index = 0; index < 10; index += 1) {
                  ctx.strokeRect(x + fieldSize * index, y, fieldSize, screenSize);
                  ctx.strokeRect(x, y + fieldSize * index, screenSize, fieldSize);
              }

2023-06-11 07:08 UTC, OlegPeunov commented
Спасибо вне справки, поменял пулл реквест на dev вместо main

2023-06-13 08:52 UTC, practicum-maxim-zyryanov approved these changes
Approve даю, но всё равно считаю, что излишне пока усложняешь, даже интересно куда зайдёт решение. Тем не менее, спасибо за ответы в комментариях к прошлому ревью, мотивацию твою понимаю. Пока рекомендую всё же вынести функции `renderMainField`, `renderBattlefield`, `renderHorizontalText` и `renderShips`, т.к. сейчас `useEffect` включает просто безразмерное тело, с которым сложно работать, но тут спасибо, что оставляешь хотя бы комментарии.

2023-06-18 09:29 UTC, merged