Feature/rooms 36
rpserjo/praktikum-game pull request #17
Opened 2023-06-16 21:37 UTC by rpserjo

### Какую задачу решаем
Добавить Redux-хранилище
В проект добавлен redux-toolkit. Создан слайс для юзера. После авторизации информацию о юзере добавляется в слайс. При обновлении данных пользователя данные в слайсе обновлются
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-17 06:26 UTC, RuslanBely approved these changes
Привет, предлагаю зафиксировать версии и посмотри насколько нужна кнопка Вход в хэдэре.

2023-06-17 06:26 UTC, RuslanBely commented on packages/client/package.json
> +        "@reduxjs/toolkit": "^1.9.5",
Наверное нужно зафиксировать версию

2023-06-17 06:26 UTC, RuslanBely commented on packages/client/package.json
> +        "redux": "^4.2.1"
и здесь версию зафиксировать.

2023-06-17 06:26 UTC, RuslanBely commented on packages/client/package.json
> +        "@types/redux": "^3.6.0",
фикс версии

2023-06-17 06:26 UTC, RuslanBely commented on packages/client/src/components/header/header.tsx
> +                )}
А мы эту кнопку в каком случае увидим? Вроде как если неавторизован, перенаправление идет на signin

2023-06-17 09:29 UTC, rpserjo commented on packages/client/package.json
> +        "@reduxjs/toolkit": "^1.9.5",
Согласен, упустил

2023-06-17 09:30 UTC, rpserjo commented on packages/client/package.json
> +        "redux": "^4.2.1"
Согласен, упустил

2023-06-17 09:31 UTC, rpserjo commented on packages/client/src/components/header/header.tsx
> +                )}
Да, верно. Я ее добавил на этапе отладки, уже после осознал, что до нее неавторизованный пользователь не доберется

2023-06-17 16:23 UTC, Olegas requested changes
Все супер, но есть два небольших замечания. Давайте их исправим

2023-06-17 16:23 UTC, Olegas commented on packages/client/src/App.tsx
> +        const checkUser = async () => {
Функция заявлена как async. Но внутри нет ни одного await.

2023-06-17 16:23 UTC, Olegas commented on packages/client/src/components/header/header.tsx
> +    const userState = useSelector((state: { user: TState }) => state.user);
Тип для стейта не надо описывать руками. Его можно вывести из определения вашего стейта. Посмотрите тут https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-state-type как это можно сделать

2023-06-17 21:07 UTC, rpserjo commented on packages/client/src/components/header/header.tsx
> +    const userState = useSelector((state: { user: TState }) => state.user);
Спасибо, не знал о такой возможности

2023-06-17 21:07 UTC, rpserjo commented on packages/client/src/App.tsx
> +        const checkUser = async () => {
Исправлено

2023-06-18 06:58 UTC, Olegas approved these changes

2023-06-18 12:26 UTC, merged