feature/ROOMS-37_canvas_dev
rpserjo/praktikum-game pull request #21
Opened 2023-06-18 13:14 UTC by OlegPeunov

Анимации игры 
drag and drop кораблей

2023-06-18 16:17 UTC, Makso-87 approved these changes

2023-06-18 16:17 UTC, Makso-87 commented on packages/client/src/pages/game/game.tsx
> +
Тип лучше неверное не внутри компонента объявлять, а за его пределами. Ну и лучше имя тиа писать с большой буквы.
<img width="383" alt="image" src="https://github.com/rpserjo/praktikum-game/assets/30118222/3c5c1922-6de5-45c5-a9e3-af9a401932fc">

2023-06-18 16:17 UTC, Makso-87 commented on packages/client/src/pages/game/game.tsx
> +
Тоже самой про типы

2023-06-18 16:17 UTC, Makso-87 commented on packages/client/src/pages/game/game.tsx
> +
Модельки кораблей тоже имеет смысл вынести в отдельный файл.

2023-06-19 16:06 UTC, Olegas commented
Всем привет! А что это за задача из бэклога?

2023-06-19 16:16 UTC, Olegas requested changes
Есть замечания по коду + надо исправить замечания коллег по команде

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +    const drawCanvasItems = function () {
Не выглядит так, что эту функцию надо объявлять внутри. Лучше вынести наружу что бы при каждом вызове не определять новую и нагружать тем самым garbage collector

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
>              const roundRect = function <T extends number>(
Аналогично. Нет повода объявлять каждый раз новую, вполне можно вынести а контекст передать через аргументы

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +            // eslint-disable-next-line
А какое правило вы тут отключаете? О чем тут говорит линтер? Если проблему нельзя исправить и надо именно отключить правило - хороший тон написать рядом комментарий что вы сделали и зачем.

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
>              // eslint-disable-next-line
Очень много правил отключено. Точно это все нужно делать? Ведь линтер на то и линтер что бы писать код по правилам.

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +            function renderShips(shipsImg: ships) {
Еще одна функция на вынос

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
>                      image.src = `../../../../public/sprites/ship_${i}.svg`;
Проверьте на production-сборке, мне кажется этот путь может сломаться

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +                // data.currnetShip.currentTop = canvasY - differenceOfShipClickY;
Не надо оставлять закомментированный код

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +        window.addEventListener('keydown', rotate);
Если подписались на событие, нужно не забыть отписаться при разрушении компонента

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +    const isMouseInShape = function <T extends number>(x: T, y: T, ship: ship): boolean {
А для чего T extends number? Какие тут могут быть типы, которые расширяют number?

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +    const isMouseInShape = function <T extends number>(x: T, y: T, ship: ship): boolean {
Также эту функцию имеет смысл вынести даже за границу компонента т.к. она чистая и зависит только от своих аргументов

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +        data.isMoucePressed = false;
Опечатка в слове mouse

2023-06-19 16:16 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +            }
А если канваса нет (ref.current пустой), разве надо что-то дальше пытаться делать?

2023-06-23 12:32 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +    const drawCanvasItems = function () {
![Screenshot 2023-06-23 at 15 31 59](https://github.com/rpserjo/praktikum-game/assets/50010781/9eddac65-1075-465a-99aa-7963dbfde191)
Спасибо, вынес функцию отдельно

2023-06-23 13:50 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
>              const roundRect = function <T extends number>(
Сори, здесь не очень понял
clearRect один раз только вызывается

2023-06-23 13:52 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +            // eslint-disable-next-line
Да, видимо она что-то другое здесь отключала. Удалил

2023-06-23 13:56 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +            function renderShips(shipsImg: ships) {
Спасибо, вынес

2023-06-23 13:57 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
>                      image.src = `../../../../public/sprites/ship_${i}.svg`;
Спасибо, поменял логику работы с путями
image.src = `./sprites/ship_${i}.svg`;

2023-06-23 14:01 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
>              // eslint-disable-next-line
Исправили это правило, и убрал отключение строки здесь

2023-06-23 14:16 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +        window.addEventListener('keydown', rotate);
![Screenshot 2023-06-23 at 17 11 49](https://github.com/rpserjo/praktikum-game/assets/50010781/715d25a6-8b82-40f7-bbf2-392c82194170)
Спасибо, добавил ремувлистенер

2023-06-23 14:19 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +            }
Добавил else {return}

2023-06-23 14:22 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +                // data.currnetShip.currentTop = canvasY - differenceOfShipClickY;
Да, сори, сейчас дописал эту часть кода и убрал все комменты

2023-06-23 14:25 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
>              const roundRect = function <T extends number>(
спасибо, вынес roundRect

2023-06-23 14:31 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +    const isMouseInShape = function <T extends number>(x: T, y: T, ship: ship): boolean {
Да, что-то перецсложнил немного
Вынес и переписал на:
const isMouseInShape = function (x: number, y: number, ship: ship): boolean {

2023-06-23 14:32 UTC, OlegPeunov commented
Спасибо, внес правки, отрефакторил ротацию корабля

2023-06-23 17:46 UTC, Olegas requested changes
Стало лучше, но не до конца.
Основные замечания прежние, какая-то общая проблема
1. Много строк где просто отключен eslint для одной строки без объяснения причин. Надо либо не отключать и написать код так, что бы линтер не ругался либо написать комментарий что именно отключается и зачем. И лучше не делать disable-next-line а отключать конкретное правило с которым проблемы
2. Много функций, которые вложены друг в друга но при этом чистые и могут быть вынесены наружу

2023-06-23 17:46 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +type ship = {
Названия типов должны быть с большой буквы - Ship

2023-06-23 17:46 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +type dataType = {
Тут аналогично - DataType

2023-06-23 17:46 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +// eslint-disable-next-line
Что вы тут отключаете? Если отключаете правило линтера - нужно написать что и зачем. Потому что обычно правила линтера стоят на проекте не просто так.
Я писал об этом еще в прошлом наборе замечаний

2023-06-23 17:46 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +    function drawShip(ctxPassed: CanvasRenderingContext2D, ship: ship, image: HTMLImageElement) {
Зачем функция вложена в renderShips если она полностью чистая? Надо вынести наружу что бы не создавать ее каждый раз и не нагружать Garbage Collector. Нечто подобное я писал на предыдущем ревью...

2023-06-23 17:46 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +const roundRect = function <T extends number>(
Для чего нужен дженерик тут? Почему просто вместо T не написать number? Какие еще могут тут быть другие типы, расширяющие number?

2023-06-24 06:12 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +type ship = {
Точно, спасибо, поменял все типы на заглавные буквы

2023-06-24 06:15 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +const roundRect = function <T extends number>(
Просто было интересно поэксперементировать с ts
Указал типы напрямую👍
![Screenshot 2023-06-24 at 09 15 13](https://github.com/rpserjo/praktikum-game/assets/50010781/c3085e5b-f623-42b5-8cc4-cff9ffa7d253)

2023-06-24 06:23 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +    function drawShip(ctxPassed: CanvasRenderingContext2D, ship: ship, image: HTMLImageElement) {
Вынес drawShip за переделы renderShips

2023-06-24 06:30 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +// eslint-disable-next-line
убрал все eslint-disable-next-line 👍

2023-06-24 08:42 UTC, Olegas requested changes
Супер, уже почти идеально. Но есть еще проблемы. Написал комментарии по ним.

2023-06-24 08:42 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +    const rotate = (event: KeyboardEvent) => {
Вот тут ошибка. rotate будет каждый раз разная (после каждого рендера компонента Game) и на 270 строке отписка от события не произойдет (потому что подписали одну функцию а отписали уже другую, хоть и с таким же телом внутри)

2023-06-24 08:42 UTC, Olegas commented on packages/client/src/pages/game/game.tsx
> +    const isDraggedIntoDropField = function (): boolean {
Еще одна функция которая не зависит, если не ошибаюсь, от данных компонента, зависит только от data, которая уже за пределами компонента

2023-06-25 06:36 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +    const isDraggedIntoDropField = function (): boolean {
да, точно, вынес за пределы компонента

2023-06-25 08:39 UTC, OlegPeunov commented on packages/client/src/pages/game/game.tsx
> +    const rotate = (event: KeyboardEvent) => {
Добавил useCallback функции 
![Screenshot 2023-06-25 at 11 38 03](https://github.com/rpserjo/praktikum-game/assets/50010781/057b215d-22a9-4436-9a1c-7e1206bfa954)

2023-06-26 19:38 UTC, Olegas approved these changes

2023-06-28 18:40 UTC, merged