Feature/rooms 40
rpserjo/praktikum-game pull request #28
Opened 2023-07-03 22:12 UTC by rpserjo

### Какую задачу решаем
Настроить Express для Server Side Rendering (без Redux, просто отдавать React-страничку)
[ROOMS-40](https://linear.app/the-rooms/issue/ROOMS-40/nastroit-express-dlya-server-side-rendering-bez-redux-prosto-otdavat)
#### Для запуска локального сервера с SSR

- перейти в папку с клиентом `cd packages/client` и выполнить команду `yarn unlink` (на всякий случай)
- собрать клиентскую часть, выполнив поочередно команды `yarn build` и `yarn build:ssr`
- создать символическую ссылку на пакет клиентской части `yarn link`
- перейти в папку с сервером `cd ../server` и добавить ссылку на пакет клиентской части приложения `yarn link client`
- собрать сервер `yarn build`
- запустить локально сервер `node dist/index.js`
- для запуска локального сервера с SSR в режиме разработки необходимо выполнить `cross-env NODE_ENV=development node dist/index.js`

### Скриншоты/видяшка (если есть)
![image](https://github.com/rpserjo/praktikum-game/assets/20280355/f5b9d357-e4b0-4b43-9080-8922f484b533)
### TBD (если есть)

2023-07-04 15:54 UTC, RuslanBely approved these changes
У меня вопросов, нет. Хорошо, что добавил инструкцию по билду)

2023-07-07 14:55 UTC, Olegas commented on packages/client/src/main.tsx
> +// startServiceWorker();
Почему это закомментировано?
С каждым новым PR функционал не должен ухудшаться.
Или тут забыли убрать комментарий или оно почему-то не работает?  Надо вернуть serviceWorker в проект.
Если оно подключается где-то в другом месте (я правда не нашел), то тут надо убрать закомментированный код.

2023-07-07 14:55 UTC, Olegas requested changes
Кажется потерян функционал serviceWorker. Написал комментарий в коде. Нужно доработать.

2023-07-07 19:09 UTC, rpserjo commented on packages/client/src/main.tsx
> +// startServiceWorker();
На установочной встрече в начали спринта ментор нашей команды рекомендовал отключить serviceWorker , поскольку он будет мешать SSR.
Собственно, с этой проблемой я и столкнулся в процессе решения данной задачи: если оставить serviceWorker незакомментированным, то при первом запуске сервера с SSR в _**production**_ окружении произойдет кеширование приложения и при перезапуске сервера в **_development_** окружении HMR перестает работать до тех пор, пока кеш не будет очищен.

2023-07-08 11:04 UTC, Olegas approved these changes

2023-07-08 14:25 UTC, merged