get leaderboard data tes
rpserjo/praktikum-game pull request #29
Opened 2023-07-08 11:45 UTC by OlegPeunov

### LeaderBoard API

2023-07-15 17:18 UTC, Makso-87 reviewed
Оставил пару замечаний

2023-07-15 17:18 UTC, Makso-87 commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        items = data.slice((+page! - 1) * 10, +page! * 10);
А что за интересное применение восклицательного знака после операнда? Знаю только применения перед операндом - операцию инверсии. А после операнда - не знаю, нагуглить не смог.

2023-07-15 17:18 UTC, Makso-87 commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +    let data = null;
Я бы не объявлял много переменных, а создал бы объект с ключами как имена переменных и спокойненько в них писал данные. Лучше избегать использование переменных без крайней необходимости.

2023-07-15 17:22 UTC, OlegPeunov commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        items = data.slice((+page! - 1) * 10, +page! * 10);
Я тоже не знаю, это из кода максима 🙈

2023-07-15 17:52 UTC, OlegPeunov commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +    let data = null;
![Screenshot 2023-07-15 at 20 51 23](https://github.com/rpserjo/praktikum-game/assets/50010781/c3627404-7ae8-4158-a712-c7b622cbc4e7)
Спасибо, вынес переменные в pageData

2023-07-15 19:26 UTC, Olegas requested changes
Добрый вечер.
Есть вещи, которые нужно исправить. Написал комментарии к проблемным местам.

2023-07-15 19:26 UTC, Olegas commented on packages/client/src/api/LeaderBoardApi.ts
> +// import { SignInData, SignUpData, TProfileProps } from '@/models/models';
Не надо оставлять закомментированный код

2023-07-15 19:26 UTC, Olegas commented on packages/client/src/api/LeaderBoardApi.ts
> +    public async postLeaderboardData(data: any): Promise<void> {
Вот здесь тип data вполне известен, можно его описать.

2023-07-15 19:26 UTC, Olegas commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        getBoardData();
А зачем тут так сложно? Зачем объявляется отдельная функция? Почему просто этот код внутри эффекта не написать? Если ради async - так он не используется в итоге...

2023-07-15 19:26 UTC, Olegas commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +                });
Вот эти бы вещи надо убрать в thunk. В этом компоненте по идее должен быть один dispatch который загружает leaderboard. А уже в async thunk загрузка. И написаны редьюсеры для всех типовых состояний - pending/completed/error в которых обновляется стейт.

2023-07-15 19:26 UTC, Olegas commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        pageData.data = leaderBoardState.leaderBoard.map(userData => userData.data);
Тут творится что-то очень странное. Зачем компонент что-то сохраняет в глобальную переменную? У вас есть стейт в redux - берите все из него. Если надо что-то свое локальное - возьмите useState. Но в глобальную переменную - точно не дело.

2023-07-16 08:03 UTC, OlegPeunov commented on packages/client/src/api/LeaderBoardApi.ts
> +// import { SignInData, SignUpData, TProfileProps } from '@/models/models';
Спасибо, удалил

2023-07-16 08:12 UTC, OlegPeunov commented on packages/client/src/api/LeaderBoardApi.ts
> +    public async postLeaderboardData(data: any): Promise<void> {
![Screenshot 2023-07-16 at 11 11 52](https://github.com/rpserjo/praktikum-game/assets/50010781/6dfa1a8e-a2b8-400d-a19a-6dae010de40f)
Спасибо, описал тип для даты

2023-07-16 08:36 UTC, OlegPeunov commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        pageData.data = leaderBoardState.leaderBoard.map(userData => userData.data);
Спасибо, переделал на useState

2023-07-16 08:37 UTC, OlegPeunov commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +                });
переделал эту часть на useState

2023-07-16 08:40 UTC, OlegPeunov commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        getBoardData();
Спасибо, убрал лишнюю обертку в useState
![Screenshot 2023-07-16 at 11 39 08](https://github.com/rpserjo/praktikum-game/assets/50010781/aa418155-bc87-42c6-ad54-cb03c280d520)

2023-07-16 09:19 UTC, Olegas commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        pageData.isShowNext = page && +page < pageData.lastPage ? true : undefined;
pageData ну убрана. Ее быть не должно вообще. Не должно быть тут глобальных переменных.

2023-07-16 09:19 UTC, Olegas requested changes
Замечание с pageData не исправлено. Нужно доделать.

2023-07-16 10:17 UTC, OlegPeunov commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        pageData.isShowNext = page && +page < pageData.lastPage ? true : undefined;
Проблема именно в том, что pageData находится за пределами компонента, правильно?
Перенес её в   
![Screenshot 2023-07-16 at 13 13 21](https://github.com/rpserjo/praktikum-game/assets/50010781/c0a13b12-d5b8-436f-adbc-4cb8f307d2a4)

2023-07-16 11:36 UTC, Olegas commented on packages/client/src/pages/leaderboard/leaderboard.tsx
> +        pageData.isShowNext = page && +page < pageData.lastPage ? true : undefined;
Да, именно в этом. Если у вас например окажется на экране два компонента таких, они дружно перетрут глобальную переменную. Вообще стоит в принципе избегать глобальных переменных.

2023-07-16 11:36 UTC, Olegas approved these changes

2023-07-16 13:47 UTC, Makso-87 approved these changes

2023-07-17 15:21 UTC, merged