Feature/rooms 42 make o auth
rpserjo/praktikum-game pull request #31
Opened 2023-07-09 14:28 UTC by Makso-87

### Какую задачу решаем
Добавлена OAuth авторизация через Яндекс.

### Скриншоты/видяшка (если есть)
<img width="1773" alt="image" src="https://github.com/rpserjo/praktikum-game/assets/30118222/31e7028e-7474-42ac-a6c5-d5ab0feb5317">

### TBD (если есть)

2023-07-09 18:29 UTC, rpserjo approved these changes
Пара предложений от меня, а так все супер!)

2023-07-09 18:29 UTC, rpserjo commented on packages/client/src/components/loginForm/loginForm.module.scss
Мне как-то "резанула" глаза черная кнопка)) Может ей другой цвет фона поставить? (#3f4151)
![image](https://github.com/rpserjo/praktikum-game/assets/20280355/3a1a7360-0436-4c6b-836b-d5529c485d88)

2023-07-09 18:29 UTC, rpserjo commented on packages/client/src/components/loginForm/loginForm.tsx
> +const oauthProviderUri = 'https://oauth.yandex.ru/authorize?response_type=code';
Наверное лучше вынести эту константу в api.ts

2023-07-09 18:32 UTC, Makso-87 commented on packages/client/src/components/loginForm/loginForm.module.scss
Да, тоже думал посветлее, но решил взять яндексовские цвета (подсмотрел где-то у яндекса). Да, сделаю посветлее.

2023-07-09 18:33 UTC, Makso-87 commented on packages/client/src/components/loginForm/loginForm.tsx
> +const oauthProviderUri = 'https://oauth.yandex.ru/authorize?response_type=code';
Тоже думал куда-то ее вынести. Но спешил и забыл )

2023-07-09 21:57 UTC, IvanPeleshok commented on packages/client/src/api/OAuthApi.ts
> +        return result
Предлагаю переписать на async / await + try / catch 
https://learn.javascript.ru/async-await

Код так будет читаемее

2023-07-09 21:57 UTC, IvanPeleshok commented on packages/client/src/api/OAuthApi.ts
> +        result
Аналогично

2023-07-09 21:59 UTC, IvanPeleshok commented on packages/client/src/components/loginForm/loginForm.tsx
> +const getOAuth: MouseEventHandler<HTMLButtonElement> = async (e: MouseEvent<HTMLButtonElement>) => {
Предлагаю вынести в отдельный модуль (файл)

2023-07-09 22:00 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-10 08:58 UTC, Makso-87 commented on packages/client/src/api/OAuthApi.ts
> +        return result
Согласен, переделал.

2023-07-10 08:58 UTC, Makso-87 commented on packages/client/src/api/OAuthApi.ts
> +        result
Переделал.

2023-07-10 08:58 UTC, Makso-87 commented on packages/client/src/components/loginForm/loginForm.tsx
> +const getOAuth: MouseEventHandler<HTMLButtonElement> = async (e: MouseEvent<HTMLButtonElement>) => {
Вынес в отдельный файл.

2023-07-10 11:42 UTC, IvanPeleshok approved these changes

2023-07-10 12:39 UTC, merged