Feature/rooms 42 ssr redux and static router
rpserjo/praktikum-game pull request #32
Opened 2023-07-09 18:32 UTC by RuslanBely

### Какую задачу решаем
ROOMS-41 Настроить Redux и Router в SSR
https://linear.app/the-rooms/issue/ROOMS-41

Реализовано использование хранилища redux на сервере, с последующей передачей начального состояния на клиент.

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-09 20:09 UTC, Makso-87 approved these changes

2023-07-11 14:24 UTC, IvanPeleshok commented on packages/client/src/api/UserService.ts
> +    // eslint-disable-next-line
Почему ругается?

2023-07-11 14:24 UTC, IvanPeleshok commented on packages/client/src/repository/YandexAPIRepository.ts
> +    // eslint-disable-next-line
Почему ругается?

2023-07-11 14:26 UTC, IvanPeleshok commented on packages/server/index.ts
> +            let mod: SSRModule;
Предлагаю не сокращать названия, ведь код мы пишем для других разработчиков

2023-07-11 14:26 UTC, IvanPeleshok requested changes
Есть вопросы и одно замечания

2023-07-12 06:29 UTC, RuslanBely commented on packages/client/src/api/UserService.ts
> +    // eslint-disable-next-line
Eslint не понимает, что это сокращенная запись класса 
```
9:5   error  Useless constructor                      no-useless-constructor
9:47  error  Unexpected empty constructor             no-empty-function
```

Если написать так, то ошибки нет:
```
export class UserService {
    private repo: UserRepository;

    constructor(repo: UserRepository) {
        this.repo = repo;
    }
```
Получается 3  варианта:
1. Указываем обход этой строки для eslint
2. Описываем класс подробно
3. Из-за частного случая правим конфиг eslint

Что порекомендуешь?

2023-07-12 06:29 UTC, RuslanBely commented on packages/client/src/api/UserService.ts
> +    // eslint-disable-next-line
Eslint не понимает, что это сокращенная запись класса 
```
9:5   error  Useless constructor                      no-useless-constructor
9:47  error  Unexpected empty constructor             no-empty-function
```

Если написать так, то ошибки нет:
```
export class UserService {
    private repo: UserRepository;

    constructor(repo: UserRepository) {
        this.repo = repo;
    }
```
Получается 3  варианта:
1. Указываем обход этой строки для eslint
2. Описываем класс подробно
3. Из-за частного случая правим конфиг eslint

Что порекомендуешь?

2023-07-12 07:26 UTC, RuslanBely commented on packages/client/src/repository/YandexAPIRepository.ts
> +    // eslint-disable-next-line
Метод внутри класса `getUserData()` называется одинаково с методом внешнего класса `authApi`, при вызове метода внешнего класса eslint думает, что это внутренний.

` 6:5  error  Expected 'this' to be used by class async method 'getUserData'  class-methods-use-this`

2023-07-12 07:27 UTC, RuslanBely commented on packages/server/index.ts
> +            let mod: SSRModule;
Спасибо, исправил.

2023-07-12 11:03 UTC, IvanPeleshok commented on packages/client/src/api/UserService.ts
> +    // eslint-disable-next-line
Во-первых, не очень понятно почему в этом файле объявляется интерфейс UserRepository (его точно необходимо вынести в место определения)
Во-вторых, этот код должен отрабатывать адекватно

К примеру, смотрел на https://www.typescriptlang.org/play
![image](https://github.com/rpserjo/praktikum-game/assets/70073003/13e7c512-413b-4533-becb-d8a0d29fa84d)

В данном случае, предлагаю поправить конфиг относительно "пустого конструктора"

2023-07-12 11:05 UTC, IvanPeleshok commented on packages/client/src/repository/YandexAPIRepository.ts
> +    // eslint-disable-next-line
Аналогично, ерунда какая-то
eslint должен помогать, а не заставлять от него избавляться (поправить линтер)

2023-07-12 11:05 UTC, IvanPeleshok requested changes
Поправить eslint

2023-07-13 06:28 UTC, IvanPeleshok approved these changes

2023-07-14 17:29 UTC, merged