notification service added, sound service added
rpserjo/praktikum-game pull request #35
Opened 2023-07-18 16:50 UTC by Hellga2023

### Какую задачу решаем

Добавлено Notification Api и Sound Api к игре. Созданы специальные сервисы для нотификаций и звуков. Кнопки включения звука и перехода в полноэкранный режим вынесены в отдельные компоненты для более читаемого кода

### Скриншоты/видяшка (если есть)

[Запись экрана от 2023-07-18 20.45.12.webm](https://github.com/rpserjo/praktikum-game/assets/126746758/9c21e8d0-666a-4487-9683-c96b6eb2392d)

### TBD (если есть)

В сервисах сделаны заготовки методов для игры, после реализации игры можно добавить звуки и нотификации для попадания в корабль, для звукового эффекта при выстреле и т.п.

2023-07-18 19:22 UTC, Makso-87 reviewed
Оставил пару замечаний

2023-07-18 19:22 UTC, Makso-87 commented on packages/client/src/pages/game/apiButtons/buttons.module.scss
> +@mixin buttonsPosition {
Миксин лучше вынести в файл с переменными scss
/packages/client/src/assets/variables.scss

2023-07-18 19:22 UTC, Makso-87 commented on packages/client/src/utils/sound/soundService.ts
> +
Здесь ты при каждом вызове метода класса создаешь экземпляр класса Audio и сразу его вызываешь. Не лучше ли будет создать сразу все экземпляры звуков при создании экземпляра класса SoundService, положить их в соответствующие свойства класса, а в методах вызывать метод play у нужного звука (свойства класса SoundService)?
```javascript
class SoundService {
    private startSound = new Audio(GameStartSound);

    playStartSound = () => {
        this.startSound.play();
    };
}
```

2023-07-19 06:07 UTC, Hellga2023 commented on packages/client/src/pages/game/apiButtons/buttons.module.scss
> +@mixin buttonsPosition {
done

2023-07-19 06:26 UTC, Hellga2023 commented on packages/client/src/utils/sound/soundService.ts
> +
done

2023-07-19 08:25 UTC, Makso-87 approved these changes

2023-07-19 09:55 UTC, IvanPeleshok commented on packages/client/src/pages/game/apiButtons/fullScreenButton.tsx
> +        if (!document.fullscreenElement) {
Предлагаю переписать колбеки на async / await + try / catch
Таким образом, код будет читаемее
https://learn.javascript.ru/async-await

2023-07-19 09:56 UTC, IvanPeleshok requested changes
Небольшое замечание

2023-07-19 12:40 UTC, merged

2023-07-19 19:15 UTC, IvanPeleshok commented
@Hellga2023, подскажи, пожалуйста, по PR нет апрува
Почему был сделан мерж?
Предлагаю почитать правила сдачи задачек в практикуме :)

2023-07-26 11:23 UTC, Hellga2023 commented
> @Hellga2023, подскажи, пожалуйста, по PR нет апрува Почему был сделан мерж? Предлагаю почитать правила сдачи задачек в практикуме :)

Невнимательно смотрела, думала что апрув уже стоит

2023-07-26 12:40 UTC, IvanPeleshok commented
> > @Hellga2023, подскажи, пожалуйста, по PR нет апрува Почему был сделан мерж? Предлагаю почитать правила сдачи задачек в практикуме :)
> 
> Невнимательно смотрела, думала что апрув уже стоит

Переведи тикет на проверку, заапрувлю без лишних действий
PR ок, всё хорошо
В следующий раз повнимательнее)

2023-07-26 12:56 UTC, Hellga2023 commented
Послала еще раз на проверку этот пул реквест в практикуме