Feature/rooms 48 db api forum
rpserjo/praktikum-game pull request #37
Opened 2023-07-20 14:51 UTC by RuslanBely

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-22 19:29 UTC, Makso-87 approved these changes

2023-07-23 09:38 UTC, Olegas requested changes
Отличная работа!
1. Валидация данных - отлично!
2. Выделили класс для типовых ответов-ошибок - лайк!
3. Разделили контроллеры и сервисы - правильно.
4. Добавлена документация на API и запуск сервера БД - отлично!

Есть замечания по коду. В основном к моделям (индексы) и запросами. Все комментарии написал отдельными сообщениями. Нужно их исправить.

Есть моменты в реализации, которые не понял. Например зачем сохранять пользовательскую куку авторизации у себя в БД. Прошу объяснить, зачем такое решение применено.

2023-07-23 09:38 UTC, Olegas commented on packages/client/src/store/index.ts
> +        // eslint-disable-next-line
А что тут отключается? Совет: не отключайте линтер для строки целиком. Если нужно отключить какое-то правило - отключите только его, а не всю проверку. Также напишите комментарий - зачем понадобилось отключать правило и почему без этого не обойтись

2023-07-23 09:38 UTC, Olegas commented on packages/server/controllers/comment-controller.ts
> +            return console.log(error);
Кажется здесь проблемы. Запрос не завершен никак и управление не передано дальше. Судя по всему, в случае ошибки запрос просто повиснет

2023-07-23 09:38 UTC, Olegas commented on packages/server/controllers/comment-controller.ts
> +            return console.log(error);
Тут аналогичная проблема

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/proxy-auth-service.ts
> +    async addCookie(Cookie: string, login?: string) {
Нужен ли тут async? Он не используется.

2023-07-23 09:38 UTC, Olegas commented on packages/server/models/auth.ts
> +    authCookie: {
А для чего нужно сохранять кукисы авторизации пользователя у себя в сервисе?

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/comment-service.ts
> +    async createComment(message: string, TopicId: number, UserId: number) {
async лишний, он не используется тут

2023-07-23 09:38 UTC, Olegas commented on packages/server/models/comment.ts
> +};
У модели комментария явно должна быть связь с топиком, к которому комментарий принадлежит. Эта связь ставится в db.ts - это немного сбивает с толку при чтении, но допустим ок.
Есть вторая проблема. Не хватает индекса на topicId т.к. именно по нему вы ищете комментарии их данного топика

2023-07-23 09:38 UTC, Olegas commented on packages/server/models/reply.ts
> +};
Тут видимо не хватает индекса по идентификатору комментария, на который написан reply

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/proxy-auth-service.ts
> +        const parseCookie = Cookie.match(/.*authCookie=([^;]*);.*Expires=(.+GMT);.*uuid=([\w-]*)/);
Нельзя ли разбор cookie отдать на откуп какой-то библиотеке? Не может ли это делать какая-то мидлвара?

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/proxy-auth-service.ts
> +    async updateExpires(uuid: UUID, expires: Date) {
async лишний. Много где. Посмотри по коду - много таких мест.

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/reaction-servise.ts
> +                [Op.and]: [{ UserId: `${UserId}` }, { CommentId: `${commentId}` }],
Вот по этим полям на реакции должен быть индекс. Не видел его добавления.
Этот индекс должен быть уникальным (что бы не получилось создать несколько реакция от одного пользователя - т.к. судя по коду вы не хотите такое допустить)

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/topic-service.ts
> +            LEFT JOIN (SELECT inc."TopicId" as "topicId", max(inc."updatedAt") as "lastMessage",  count(*) \
Вот эти подзапросом вы каждый раз выбираете всю таблицу Comments. У вас не будет правильно работать count(*) здесь. Оно всегда будет равно количеству комментариев в таблице

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/topic-service.ts
> +                           FROM public."Comments" inc  GROUP BY inc."TopicId") AS c ON  c."topicId"=t.id \
Что бы работало правильно, фильтрация должна быть в подзапросе

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/topic-service.ts
> +            Order BY "lastMessageDate" DESC  \
Обрати внимание на стиль написания SQL. Часть SQL-команд написано КАПСОМ, часть просто с большой буквы. Надо стараться писать в одном стиле иначе такой код сложно читать.

2023-07-23 09:38 UTC, Olegas commented on packages/server/servises/topic-service.ts
> +        return updatableTopic.update(values);
А сам update на справится с тем что бы проверить наличие элемента прежде чем его обовлять? Точно ли нужна тут самостоятельно написанная проверка по id?

2023-07-24 05:41 UTC, RuslanBely commented on packages/client/src/store/index.ts
> +        // eslint-disable-next-line
Спасибо, видимо в момент, отладки, пока не разобрался поставил, потом забыл убрать.

2023-07-24 05:47 UTC, RuslanBely commented on packages/server/controllers/comment-controller.ts
> +            return console.log(error);
Спасибо, поправил.

2023-07-24 05:47 UTC, RuslanBely commented on packages/server/controllers/comment-controller.ts
> +            return console.log(error);
Спасибо, поправил.

2023-07-24 09:11 UTC, RuslanBely commented on packages/server/servises/proxy-auth-service.ts
> +    async addCookie(Cookie: string, login?: string) {
Да, спасибо, осознал, что если мы не обрабатываем результат можно просто вернуть вызываемый метод.

2023-07-24 09:15 UTC, RuslanBely commented on packages/server/models/auth.ts
> +    authCookie: {
В задаче есть требование по авторизации пользователя при использовании API + нам нужно понимать, какой пользователь создает сущности. Чтоб при каждом запросе пользователя в наш API не ходить в Яндекс реализован функционал, который ловит установку куки пользователю от Яндекса и записывает в БД со сроком действия. Когда пользователь идет в наш API смотрим по сохранённым куки кто это и авторизуем.

2023-07-24 09:19 UTC, RuslanBely commented on packages/server/servises/comment-service.ts
> +    async createComment(message: string, TopicId: number, UserId: number) {
Спасибо, убрал.

2023-07-24 16:23 UTC, RuslanBely commented on packages/server/models/comment.ts
> +};
Полагал, что индекс автоматом создается при создании внешнего ключа, добавил.

2023-07-24 16:26 UTC, RuslanBely commented on packages/server/models/comment.ts
> +};
> У модели комментария явно должна быть связь с топиком, к которому комментарий принадлежит. Эта связь ставится в db.ts - это немного сбивает с толку при чтении, но допустим ок

Я с Sequelize встречаюсь в первый раз, взял за образ то пример, который был в теории: https://github.com/eshturman/orm-simple-template/blob/main/app/init/index.ts

2023-07-24 16:30 UTC, RuslanBely commented on packages/server/models/reply.ts
> +};
Добавил

2023-07-24 16:33 UTC, RuslanBely commented on packages/server/servises/proxy-auth-service.ts
> +    async updateExpires(uuid: UUID, expires: Date) {
Спасибо, посмотрел, убрал

2023-07-24 16:41 UTC, RuslanBely commented on packages/server/servises/reaction-servise.ts
> +                [Op.and]: [{ UserId: `${UserId}` }, { CommentId: `${commentId}` }],
Спасибо, сделал.

2023-07-24 16:57 UTC, RuslanBely commented on packages/server/servises/topic-service.ts
> +            LEFT JOIN (SELECT inc."TopicId" as "topicId", max(inc."updatedAt") as "lastMessage",  count(*) \
WHERE где-то потерял по дороге, благодаря группировке считалось верно, но согласен, что подзапрос был совсем не оптимальный

2023-07-24 16:58 UTC, RuslanBely commented on packages/server/servises/topic-service.ts
> +                           FROM public."Comments" inc  GROUP BY inc."TopicId") AS c ON  c."topicId"=t.id \
Ответил выше

2023-07-24 16:59 UTC, RuslanBely commented on packages/server/servises/topic-service.ts
> +            Order BY "lastMessageDate" DESC  \
Согласен, поправил

2023-07-24 18:30 UTC, RuslanBely commented on packages/server/servises/topic-service.ts
> +        return updatableTopic.update(values);
Раньше думал, что нужно проверять, погуглил и понял что это просто добавит еще один скан)

2023-07-24 19:08 UTC, RuslanBely commented on packages/server/servises/proxy-auth-service.ts
> +        const parseCookie = Cookie.match(/.*authCookie=([^;]*);.*Expires=(.+GMT);.*uuid=([\w-]*)/);
Да, тут скорее всего можно cookieParser применить сходу не понял как потому по  быстрому регулярку накидал. Посмотрю позже

2023-07-24 19:19 UTC, Olegas commented on packages/server/models/auth.ts
> +    authCookie: {
Бережливое отношение к внешним API - это хорошо. Молодец!

2023-07-24 19:24 UTC, Olegas approved these changes
Отлично! Работа принята

2023-07-26 08:02 UTC, merged