Feature/rooms 53
rpserjo/praktikum-game pull request #39
Opened 2023-07-21 09:04 UTC by rpserjo

### Какую задачу решаем
[ROOMS-47](https://linear.app/the-rooms/issue/ROOMS-47/nastroit-docker-dlya-postgres)
[ROOMS-53](https://linear.app/the-rooms/issue/ROOMS-53/servernaya-infrastruktura-dlya-foruma)
#### Как запустить
Перед началом сборки необходимо выполнить `node init.js`
Для сборки контейнеров необходимо запустить `docker compose build`
Для запуска - `docker compose up`
В сборке 4 контейнера - client, server, postgres и pgadmin.
server и pgadmin запускаются после удачного запуска postgres, client - после запуска сервера.
Явки / пароли добавляются через .env
### Скриншоты/видяшка (если есть)
Client:
![image](https://github.com/rpserjo/praktikum-game/assets/20280355/677bd404-7b0b-42d2-bac0-d4f4cb568d2e)
Server:
![image](https://github.com/rpserjo/praktikum-game/assets/20280355/bfa7d121-e71f-4333-9f82-c21541ec87ef)
Docker-compose:
![image](https://github.com/rpserjo/praktikum-game/assets/20280355/24ad85f7-8ef6-4ab8-b12e-307aec2c658f)

### TBD (если есть)

2023-07-21 10:18 UTC, RuslanBely approved these changes
Approve, но прошу учесть комментарии перед объединением.

2023-07-21 10:18 UTC, RuslanBely commented on .env.sample
>  SERVER_PORT=3001
Чтоб работала авторизация через OAuth нужно чтоб локально сервер запускался на 3000 порту.
```suggestion
CLIENT_PORT=2999
SERVER_PORT=3000
```

2023-07-21 10:18 UTC, RuslanBely commented on Dockerfile.client
> +ARG CLIENT_PORT=3000
Здесь как и ваше предлагаю оставить 3000 порт за сервером

2023-07-21 10:18 UTC, RuslanBely commented on Dockerfile.server
> +RUN yarn link
Можно сократить количество слоев образа, в теории написано, что это снижает вес образа. Но в данном случае размер не меняется.
```suggestion
RUN rm -rf /app/packages/client/dist && rm -rf /app/packages/client/ssr-dist  && \
yarn build  && \
yarn link
```

2023-07-21 10:18 UTC, RuslanBely commented on Dockerfile.server
> +RUN yarn build
Сокращение слоев
```suggestion
RUN rm -rf /app/packages/server/dist  && \
yarn link client  && \
yarn build  && \
```

2023-07-21 10:18 UTC, RuslanBely commented on Dockerfile.server
>  RUN yarn install --production=true
```suggestion
RUN yarn link client  && \
yarn install --production=true
```

2023-07-21 10:18 UTC, RuslanBely commented on packages/client/src/api/api.ts
> +const HOST = 'http://localhost:3001/api/v2';
Как и выше предлагаю оставить 3000 порт за сервером

2023-07-21 10:18 UTC, RuslanBely commented on packages/server/package.json
> +    "build": "rm -rf ./dist && tsc --p ./tsconfig.prod.json",
на маке у Олега вроде была проблема при билде с удалением несуществующей папки, если -f решит это вопрос предлагаю оставить. Если нет, предлагаю для сборки создать отдельную команду.

2023-07-21 11:53 UTC, rpserjo commented on packages/server/package.json
> +    "build": "rm -rf ./dist && tsc --p ./tsconfig.prod.json",
Да, как раз на маке с такой же ошибкой столкнулся и это позволило её решить

2023-07-21 12:04 UTC, rpserjo commented on packages/client/src/api/api.ts
> +const HOST = 'http://localhost:3001/api/v2';
fixed

2023-07-21 14:13 UTC, IvanPeleshok commented on docker-compose.yml
> +
Предлагаю добавить пустую строку и вот почему https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2023-07-21 14:14 UTC, IvanPeleshok requested changes
Есть замечания от тимейтов

2023-07-21 20:38 UTC, rpserjo commented on docker-compose.yml
> +
еще одну?

2023-07-23 12:49 UTC, IvanPeleshok approved these changes

2023-07-23 18:13 UTC, merged